In [6]:
import numpy as np
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


# for wide mathematical application we use numpy 

#  %time it gives time of excution for single programme

#  %%time it gives time of excution for entire programme

In [10]:
%timeit [j**4 for j in range(1,9)]

483 ns ± 6.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [11]:
import numpy as np
%timeit np.arange(1,9)**4

1.46 µs ± 45.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# creating numpy arrays

In [12]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [17]:
l = []

for i in range(5):
    int_i = int(input("enter: "))
    l.append(int_i)
m = np.array(l)
print(np.array(l))
# print(type(l))
print(type(m))

enter:  1
enter:  2
enter:  3
enter:  4
enter:  5


[1 2 3 4 5]
<class 'numpy.ndarray'>


# types of arrays 1d,2d,3d, nd 

In [ ]:
# ndim function for checking the dimension of array

In [18]:
print(m.ndim)

1


In [19]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [ ]:
# for creating a 2d array it is important to have the same no. of element in the list in this case 4 elements were there

In [20]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[6,7,8,9]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [6 7 8 9]]]
3


In [ ]:
# let's create a 10 dimension array for this insted of creating 10 brackets we can use some other syntax

In [22]:
arn = np.array([1,2,3,4], ndmin=10 )
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [ ]:
# create numpy array using numpy function