# Insert and Delete function

In [2]:
import numpy as np

var = np.array([1,2,3,4])
print(var)
# syntax --> np.insert(var, index, value)
p = np.insert(var,2, 40)
print(p)

[1 2 3 4]
[ 1  2 40  3  4]


In [3]:
# for inserting multiple data at once

In [8]:
multiple_insert = np.insert(var,(2,4), 40)
print(multiple_insert)

[ 1  2 40  3  4 40]


In [9]:
# if we are inserting decimal value it will get converted into whole number

In [11]:
var_2d = np.array([[1,2,3],[1,2,3]])
print(var_2d)
var_2d = np.insert( var_2d, (2,4), 6.5)
print(var_2d)

[[1 2 3]
 [1 2 3]]
[1 2 6 3 1 6 2 3]


In [12]:
# look from the data noted we need to give axis value to

In [19]:
var_2d = np.array([[1,2,3],[1,2,3]])
var_2d = np.insert( var_2d, 2, 6.5,axis= 0)
print(var_2d)

[[1 2 3]
 [1 2 3]
 [6 6 6]]


In [20]:
# axis =1

In [26]:
var_2d = np.array([[1,2,3],[1,2,3]])
print(var_2d)
print()
var_2d = np.insert( var_2d, 2,22,axis= 1)
# work according to column
print(var_2d)

[[1 2 3]
 [1 2 3]]

[[ 1  2 22  3]
 [ 1  2 22  3]]


# .append

In [29]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)

print()
var1 = np.append(var1,[[45,44,23]], axis=0)
print(var1)

[[1 2 3]
 [1 2 3]]

[[ 1  2  3]
 [ 1  2  3]
 [45 44 23]]


# Delete

In [31]:
var = np.array([1,2,3,4])
print(var)
# syntax --> np.insert(var, index)
d = np.delete(var,2)
print(d)

[1 2 3 4]
[1 2 4]


# Numpy Matrix

In [34]:
var_mx = np.matrix([[1,2,3],[1,2,3]])
print(var_mx)
print(type(var_mx))
print()

var_ax = np.array([[1,2,3],[1,2,3]])
print(var_ax)
print(type(var_ax))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [36]:
# addition property of matrix and array is same 

In [37]:
# but not multiplication property

# addition 

In [39]:
var_mx = np.matrix([[1,2,3],[1,2,3]])
var_mx2 = np.matrix([[1,2,3],[1,2,3]])
print(var_mx)
print(var_mx2)
print()
print(var_mx + var_mx2)

[[1 2 3]
 [1 2 3]]
[[1 2 3]
 [1 2 3]]

[[2 4 6]
 [2 4 6]]


# subtraction

In [40]:
print(var_mx - var_mx2)

[[0 0 0]
 [0 0 0]]


# multiplication

In [41]:
print(var_mx * var_mx2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [45]:
var_mx = np.matrix([[1,2],[1,2]])
var_mx2 = np.matrix([[1,2],[1,2]])
print(var_mx)
print(var_mx2)
print()
print(var_mx * var_mx2)

[[1 2]
 [1 2]]
[[1 2]
 [1 2]]

[[3 6]
 [3 6]]


In [46]:
# insted

In [50]:
import numpy as np

var_mx = np.matrix([[1, 2, 3], [1, 2, 3]])
var_mx2 = np.matrix([[1, 2, 3], [1, 2, 3]])

print("Matrix 1:")
print(var_mx)
print()

print("Matrix 2:")
print(var_mx2.T)  # Transpose Matrix 2
print()

# Matrix multiplication
result = var_mx * var_mx2.T  # Use the transposed matrix

print("Result of Matrix Multiplication:")
print(result)


Matrix 1:
[[1 2 3]
 [1 2 3]]

Matrix 2:
[[1 1]
 [2 2]
 [3 3]]

Result of Matrix Multiplication:
[[14 14]
 [14 14]]


# Mattix Functions

In [51]:
# transpose of matrix

In [52]:
var_mx = np.matrix([[1, 2, 3], [4, 5, 6]])
print(var_mx)
print()

print(np.transpose(var_mx))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[1 2 3 4]


# Swapaxes

In [53]:
var_mx3 = np.matrix([[1,2],[3,4]])
print(var_mx3)
print()
print(np.swapaxes(var_mx3, 0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


# inverse matrix

In [55]:
var_mx3 = np.matrix([[1,2],[3,4]])
print(var_mx3)
print()
print(np.linalg.inv(var_mx3))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


# power of matrix

# Determinate