<!-- zeroes -->

# topics
# array filled with 0's
# array filled with 1's 
# create an empty array 
# ana array with a range of elements
# array diagonal element filled with 1's

# array filled with 0's

In [3]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# array filled with 1's 

In [4]:
ar_zero = np.ones(4)
print(ar_zero)

[1. 1. 1. 1.]


# create an empty array 

In [6]:
ar_emp = np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


# an array with a range of elements

In [8]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


#  array diagonal element filled with 1's

In [ ]:
# Diagonal

In [9]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
ar_dia2 = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# special interval array

<!-- we called this function as linspace  -->
<!-- we will create a array where equally spaced no. in between 1 and 10 will occur and the number of such element is set to be num=5 -->

In [22]:
ar_lin = np.linspace(1,10, num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]
