# create a numpy array with random number

In [2]:
 # functions that can be used: rand(), randn(), ranf(), randint()

In [5]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.45752944 0.51149109 0.69038059 0.22127213]


In [6]:
var1 = np.random.rand(2,5)
print(var1)

[[0.20948872 0.61793168 0.06605829 0.12416735 0.40420148]
 [0.39884091 0.30074782 0.84754026 0.01273242 0.09402197]]


In [ ]:
# randn() used for no close to zero can be positive or negative

In [9]:
var2 = np.random.randn(4)
print(var2)

[-0.80735961 -2.90852228 -2.40574667  0.01916976]


In [10]:
# ranf() for getting no between 0 and 1 excluding 1

In [12]:
var3 = np.random.ranf(4)
print(var3)

[0.15751654 0.52469222 0.57448239 0.40684607]


In [13]:
# randint()


In [16]:
# var4 = np.random.randint(min,max,total)
var4 = np.random.randint(5,20,5)
print(var4)

[ 7 18 10 14 11]
