# data types in numpy arrays


In [2]:
import numpy as np

var = np.array([1,2,3,4,5])
print("Data type:", var.dtype)

Data type: int32


In [9]:
var2 = np.array([1.0, 1.2, 1.3 ])
print("Data type: " , var2.dtype )

Data type:  float64


In [10]:
var3 = np.array(["a", "b", "c"])
print("Data type :", var3.dtype )

Data type : <U1


In [14]:
var3 = np.array(["a", "b", "c",1,2,3,2.2])
print("Data type :", var3.dtype )

Data type : <U32


In [ ]:
# changing one data type to another

In [15]:
var = np.array([1,2,3,4,5])
print("Data type:", var.dtype)

Data type: int32


In [16]:
var = np.array([1,2,3,4,5],dtype= np.int8)
print("Data type:", var.dtype)

Data type: int8


In [ ]:
# converting int to float

In [3]:
x1 = np.array([1,2,3,4,5],dtype= "f")
print("Data type:", x1.dtype)

Data type: float32


In [7]:
x2 = np.array([1,2,3,4,5])
new = np.float32(x2)
new_one = np.int_(new)
print("x2 Data Type: ", x2.dtype)
print("new Data Type: ", new.dtype )
print("new _one Data Type: ", new_one.dtype )
print(x2)
print(new)
print(new_one)

x2 Data Type:  int32
new Data Type:  float32
new _one Data Type:  int32
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [8]:
# astype function

In [9]:
x3 = np.array([1,2,3,4])
new_i = x3.astype(float)
print(x3)
print(new_i)

[1 2 3 4]
[1. 2. 3. 4.]
