# Shape and reshape in Numpy Arrays

In [3]:
import numpy as np
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [5]:
var1 = np.array([1,2,3,4], ndmin=4)

print(var1)
print(var1.ndim)
print()
print(var1.shape)


[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [7]:
# reshape 1d array to multi dimension or vice versa array using reshape function

In [10]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)


print()


x = var2.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [11]:
# we hace to watch the number of element while reshaping

In [12]:
# we have 6 elements and if we want to reshape like(3,3) meaning 3 rows and 3 columns then this will throw an error as the number of elements are 
# not sufficient for this 

In [14]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)


print()


x1 = var3.reshape(2,3,2)
print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [15]:
# how to move on from this 3d array back to 1d array

In [19]:
one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# arithematic operations in Numpy arrays

In [22]:
import numpy as np
var_1 = np.array([1,2,3,4])
print(var_1)
print()

varadd = var_1 + 3
print(varadd)

[1 2 3 4]

[4 5 6 7]


In [23]:
# adding to arrays

In [24]:
var_11 = np.array([1,2,3,4])
var_22 = np.array([4,3,2,1])
var_add = var_11 + var_22
print(var_add)

[5 5 5 5]


In [25]:
# subtraction

In [26]:
var_3 = np.array([1,2,3,4])
var_sub = var_3 - 3
print(var_sub)

[-2 -1  0  1]


In [27]:
# multiply

In [29]:
var_4 = np.array([1,2,3,4])
var_ml = var_4 * 3
print(var_ml)

[ 3  6  9 12]


In [30]:
# divide

In [31]:
var_5 = np.array([1,2,3,4])
var_dvd = var_5 / 3
print(var_dvd)

[0.33333333 0.66666667 1.         1.33333333]


In [32]:
# modulas

In [35]:
var_6 = np.array([1,2,3,4])
var_mod = var_6 % 3
print(var_mod)

[1 2 0 1]


In [36]:
# using functions

In [37]:
var_11 = np.array([1,2,3,4])
var_22 = np.array([4,3,2,1])

var_add_fnc = np.add(var_11, var_22 )

print(var_add_fnc)

[5 5 5 5]


In [39]:
var_11 = np.array([1,2,3,4])
# var_22 = np.array([4,3,2,1])

var_add_fnc = np.add(var_11, 1 )

print(var_add_fnc)

[2 3 4 5]


# what for 2d array

In [43]:
var_2d = np.array([[1,2,3,4],[1,2,3,4]])
var_2d2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var_2d)
print()
print(var_2d2)
print()

varadd2 = var_2d + var_2d2
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [44]:
# multiplication

In [46]:
var_2d = np.array([[1,2,3,4],[1,2,3,4]])
var_2d2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var_2d)
print()
print(var_2d2)
print()

varmd2 = var_2d * var_2d2
print(varmd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [47]:
# reciprocal

In [48]:
rp_1d = np.array([1,2,3,4])
reciprocal = np.reciprocal(rp_1d)
print(reciprocal)

[1 0 0 0]
