# Arithmetic Fucnctions
# np.min(x)
# np.max(x)
# etc.

In [7]:
import numpy as np

var = np.array([1,2,3,4,5,6])
print("min: ", np.min(var))
print("max: ", np.max(var))

min:  1
max:  6


In [4]:
# np.argmin for getting posittion of element x

In [6]:
var = np.array([1,2,3,4,5,6])
print("min: ", np.min(var), "position: " ,np.argmin(var))
print("max: ", np.max(var), "position: " ,np.argmax(var))

min:  1 position:  0
max:  6 position:  5


In [8]:
# for 2d arrays we can work along axis

In [ ]:
# concept of axis will be used for this
# we have two type of axis 0 and 1 denoting columns, rows


In [11]:
var1 = np.array([[2,1,3],[9,5,6]])
print(var1)
print()
print(np.min(var1,axis=1))

[[2 1 3]
 [9 5 6]]

[1 5]


In [12]:
# so we have 1 as minimum value in row 1 and 5 as minimum in row 2

In [13]:
# along column 

In [14]:
var1 = np.array([[2,1,3],[9,5,6]])
print(var1)
print()
print(np.min(var1,axis=0))

[[2 1 3]
 [9 5 6]]

[2 1 3]


In [15]:
# we get 2 as minimum value in column1 , 1 in col2, etc.

# SQURT

In [16]:
var = np.array([1,2,3,4,5,6])
# print("min: ", np.min(var), "position: " ,np.argmin(var))
# print("max: ", np.max(var), "position: " ,np.argmax(var))
print("SQURT: ", np.sqrt(var))

SQURT:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]


# np.sin(x)

In [18]:
var_trigo = np.array([1,2,3])
print(np.sin(var_trigo))
print(np.cos(var_trigo))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


# np.cumsum(x)

In [20]:
var_trigo = np.array([1,2,3])
print(np.cumsum(var_trigo))

[1 3 6]
