# Broadcasting Numpy arrays

In [1]:
# just simple matrix addition rules that you learn in class 12th

In [2]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
print(var1 + var2 )

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [3]:
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
print(var1 + var2 )

[2 4 6 8]


In [4]:
# comparing 1X3 or 3X1 matrics weather any operatinons are possible or not

In [11]:
var11 = np.array([1,2,3])
# print(var1.shape)
print(var11)
print()
var22 = np.array([[1],[2],[3]])
print(var22)
# print(var2.shape)

[1 2 3]

[[1]
 [2]
 [3]]


In [12]:
print(var11 + var22)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [13]:
# what for a 2X1 and 2x3 matrix

In [16]:
var21 = np.array([[1],[2]])
print(var21.shape)

(2, 1)


In [17]:
var23 = np.array([[1,2,3],[4,5,6]])
print(var23.shape)

(2, 3)


In [18]:
print(var21 + var23)

[[2 3 4]
 [6 7 8]]


# indexing and slicing in numpy arrays

# indexing

In [21]:
ind = np.array([11, 12, 13,14])
#               0,  1,  2, 3
#              -4, -3, -2, -1

print(ind[1])

12


In [22]:
# for 2d arrays

In [26]:
ind_2d = np.array([[9,8,7],[4,5,6]])
print(ind_2d)


# print(ind_2d.ndim)
print(ind_2d[0,2])

[[9 8 7]
 [4 5 6]]
7


In [27]:
# for 3d arrays

In [30]:
ind_3d = np.array([[[1,2],[6,7]]])
print(ind_3d)
print(ind_3d.ndim)
print(ind_3d[0,1,1])

[[[1 2]
  [6 7]]]
3
7


# slicing Numpy Arrays

In [32]:
# variable[start:stop:step]

In [38]:
slice = np.array([11, 12, 13,14,15,16,17,18,19,20])
print("2 to 5:  ", slice[2:5])

2 to 5:   [13 14 15]


In [39]:
print("2 to end:  ", slice[2:])

2 to end:   [13 14 15 16 17 18 19 20]


In [40]:
print("start to end with a jump:  ", slice[::2])

start to end with a jump:   [11 13 15 17 19]


In [41]:
# for 2d arrays

In [42]:
slice_2d = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(slice_2d)


[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]


In [43]:
print( "8 to 5: ", slice_2d[1,1:])

8 to 5:  [8 7 6 5]


In [44]:
# for 3d array's

In [45]:
slice_3d = np.array([[[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]]])
print(slice_3d)

[[[ 1  2  3  4  5]
  [ 9  8  7  6  5]
  [11 12 13 14 15]]]


In [46]:
print(slice_3d.ndim)


3


In [51]:
print( "12 to 15: ", slice_3d[0,2,1:])

12 to 15:  [12 13 14 15]


In [57]:
import numpy as np

slice_3d = np.array([[[1, 2, 3, 4, 5], [9, 8, 7, 6, 5]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
                    ,[[20, 21, 22, 23, 24],[25, 26, 27, 28, 29]]])
print(slice_3d)


[[[ 1  2  3  4  5]
  [ 9  8  7  6  5]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [58]:
# how to print 17 to 20?

In [60]:
print("17 to 20: ", slice_3d[1,1,1:])

17 to 20:  [17 18 19 20]
