# Iterating Numpy Arrays

In [2]:
import numpy as np

In [4]:
var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [7]:
var_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(var_2d)
print()

for j in var_2d:
    print(j)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]


In [8]:
# if we want to get hold of values like 1,2,3.. then we have to apply iteration on iteration

In [14]:
for k in var_2d:
    for l in k:
        print(l)
        

1
2
3
4
5
6
7
8


In [15]:
# for 3d array

In [16]:
var_3d = np.array([[[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]]])
print(var_3d)
print()

for i in var_3d:
    for j in i:
        for k in j:
            print(k)

[[[ 1  2  3  4  5]
  [ 9  8  7  6  5]
  [11 12 13 14 15]]]

1
2
3
4
5
9
8
7
6
5
11
12
13
14
15


In [17]:
# insted of applying for loop multiple times we can use nditer()

In [18]:
for i in np.nditer(var_3d):
    print(i)

1
2
3
4
5
9
8
7
6
5
11
12
13
14
15


In [19]:
# what if we want to change the type of data to number to string

In [27]:
for i in np.nditer(var_3d,flags=["buffered"],op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'9'
b'8'
b'7'
b'6'
b'5'
b'11'
b'12'
b'13'
b'14'
b'15'


In [29]:
# what if we want to print along with indexing this is needed in case of large data
# ndemumerate function is used

In [30]:
for i,d in np.ndenumerate(var_3d):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 9
(0, 1, 1) 8
(0, 1, 2) 7
(0, 1, 3) 6
(0, 1, 4) 5
(0, 2, 0) 11
(0, 2, 1) 12
(0, 2, 2) 13
(0, 2, 3) 14
(0, 2, 4) 15


# Copy vs View in Numpy arrays

In [4]:
var_copy = np.array([1,2,3,4])
co = var_copy.copy()

print("var: ", var_copy)
print("copy: ", co)

var:  [1 2 3 4]
copy:  [1 2 3 4]


In [38]:
var_view = np.array([9,8,7,6])
vi = var_view.view()
print("vi: ", vi)

vi:  [9 8 7 6]


In [35]:
# what if we do some changes alongwith our data let's do it

In [ ]:
# experimenting copy

In [5]:
var_copy[2]=40

print("var: ", var_copy)
print("copy: ", co)

var:  [ 1  2 40  4]
copy:  [1 2 3 4]


In [40]:
# see the data inside the copy didn't change

In [41]:
# experimenting view

In [43]:
var_view[2] = 30
print("var_view: ", var_view)
print("vi: ", vi)

var_view:  [ 9  8 30  6]
vi:  [ 9  8 30  6]


In [44]:
# see the difference between copy and view

# Join & Split Functions in Numpy Arrays

# Join Array

In [48]:
join_var1 = np.array([1,2,3,4])
join_var2 = np.array([6,7,8,9])
joined_array = np.concatenate((join_var1, join_var2))
print(joined_array)

[1 2 3 4 6 7 8 9]


In [49]:
# for 2d arrays 

In [52]:
# we need to need to dicide along which axis we want to join ie. 0,1 

In [53]:
vr1 = np.array([[1,2],[3,4]])
var2 = np.array([[9,8],[7,6]])
ar_new = np.concatenate((vr1,var2),axis=1)
print(vr1)
print()
print(var2)
print()

print(ar_new)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [55]:
ar_new = np.concatenate((vr1,var2),axis=0)
print(ar_new)

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


# using stack functions

In [5]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([6,7,8,9])

a_new = np.stack((var1, var2), axis=0)
print(a_new)

[[1 2 3 4]
 [6 7 8 9]]


In [7]:
a_new1 = np.hstack((var1,var2)) #row
print(a_new1)
print()

a_new2 = np.vstack((var1,var2)) #column
print(a_new2)
print()
a_new3 = np.dstack((var1, var2)) #height
print(a_new3)

[1 2 3 4 6 7 8 9]

[[1 2 3 4]
 [6 7 8 9]]

[[[1 6]
  [2 7]
  [3 8]
  [4 9]]]


# split array

In [12]:
var = np.array([1,2,3,4,5,6,7,8,9])
print(var)

ar = np.split(var,3)
print()
print(ar)
print()
print(type(ar))
print()
print(ar[0])

[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

<class 'list'>

[1 2 3]


In [13]:
# 2d array

In [21]:
var_2d = np.array([[1,2],[3,4],[5,6]])
print(var_2d)
print()

ar_2d = np.array_split(var_2d,3)
print(ar_2d)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [16]:
# how to split along axis

In [19]:
ar_2d = np.array_split(var_2d,3, axis=1)
print(ar_2d)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]
