# Search, Sort, Search Sorted, Filter functions

# Search

In [1]:
import numpy as np
var = np.array([4,2,3,4,2,5,2,5,6,7])
# index         0 1 2 3 4 5 6 7 8 9

x = np.where( var ==2 )
print(x)

(array([1, 4, 6], dtype=int64),)


In [ ]:
# we can also do arithmatic operations like 

In [2]:
var = np.array([4,2,3,4,2,5,2,5,6,7])
# index         0 1 2 3 4 5 6 7 8 9

x = np.where( (var%2) == 0 )
print(x)

(array([0, 1, 3, 4, 6, 8], dtype=int64),)


# search sort

In [9]:
var1 = np.array([1,2,3,5,6,7,8,9,10])
# index          0 1 2 3 4 5 6 7 8
x1 = np.searchsorted( var1, 4 )
print(x1)

3


In [6]:
# if we are looking for a proper placement of a specific value according to our array

In [7]:
# frorm right hand side

In [11]:
x1 = np.searchsorted( var1, 4 ,side="right")
print(x1)

3


In [16]:
var2 = np.array([1,2,3,5,6,10])
# index          0 1 2 3 4 5

x2 = np.searchsorted( var1,[7,8,9,4]) 
print(x2)

[5 6 7 3]


# Sort

In [ ]:
# sort is used for arraging alphabet/numbers in asecnding/descending order

In [19]:
var_1s = np.array([1,12,3,15,6,17,8,9,10])
# index            0 1  2 3  4 5  6 7 8

In [20]:
print(np.sort(var_1s))

[ 1  3  6  8  9 10 12 15 17]


In [21]:
var_2s = np.array(["a", "f", "c", "m"])
print(np.sort(var_2s))

['a' 'c' 'f' 'm']


In [22]:
# for 2d array

In [23]:
var_1s = np.array([[1,12,3],[15,6,17],[8,9,10]])
print(np.sort(var_1s))

[[ 1  3 12]
 [ 6 15 17]
 [ 8  9 10]]


# Filter

In [27]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Define a condition
condition = arr > 2

# Use filter to get elements that satisfy the condition
result = np.extract(condition, arr)

print(result)


[3 4 5]


In [28]:
# NumPy provides a powerful function called numpy.filter which is used to construct an array from elements of a given array that satisfy a certain condition.

In [29]:
print(type(result))

<class 'numpy.ndarray'>


In [30]:
var_2f = np.array(["a", "f", "c", "m"])
f =[True, False, False, True]

new_a = var_2f[f]
print(new_a)

['a' 'm']


# Shuffle, Unique, Resize, Flatten, Ravel Functions

# Shuffle

In [37]:
import numpy as np
var = np.array([1,2,3,4,5])
print(var)
print()
# sf_var = np.random.shuffle(var)
# it didn't work
np.random.shuffle(var)
print(var)

[1 2 3 4 5]

[4 2 3 5 1]


# Unique

In [39]:
var_x = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var_x)
print(x)

[1 2 3 4 5 6 7]


In [40]:
# for printing data along with its index

In [42]:
var_x = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var_x, return_index=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64))


In [43]:
# for printing the count of repetation

In [45]:
var_x = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var_x, return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([1, 4, 1, 1, 1, 1, 1], dtype=int64))


# Resize

In [48]:
var_xx = np.array([1,2,3,4,5])
y = np.resize(var_xx,(2,3))
print(y)

[[1 2 3]
 [4 5 1]]


# Flatten

In [49]:
# used to convert a 2d --> 1d

In [51]:
var_xx = np.array([1,2,3,4,5])
y = np.resize(var_xx,(2,3))
print(y)

print()
print(y.flatten())

[[1 2 3]
 [4 5 1]]

[1 2 3 4 5 1]


In [53]:
# check the matrix element carefully

In [55]:
print(y.flatten('F'))

[1 4 2 5 3 1]


In [56]:
print(y.flatten('C'))

[1 2 3 4 5 1]


In [57]:
print(y.flatten('A'))

[1 2 3 4 5 1]


In [59]:
print(y.flatten('K'))

[1 2 3 4 5 1]
